export const QueryKeys = {
  TENANTS: "TENANTS",
  USER: "USER",
  STATES: "STATES",
  LGA: "LGA",
  INDIVIDUAL: "INDIVIDUAL",
  COMPANY: "COMPANY",
  RETURNS: "RETURNS",
  BILL: "BILL",
  COMPANY_RETURNS: "COMPANY_RETURNS",
  COMPANY_RETURNS_GRAPH: "COMPANY_RETURNS_GRAPH",
  COMPANY_RETURNS_STAT: "COMPANY_RETURNS_STAT"
};
